### ISSUE TITLE
Complete Finance backlog

### ISSUE THREAD

**Issue by MmeMarieLouise** [pyladies/global-organizing#117]
# Tasks

- [ ] finish reading all psf finance docs
- [ ] draft responses to each psf finance action point
- [ ] Plan Reimbursements & expenses for PyLadies Global
- [ ] Set up process for GC to review sponsorship and Financial requests
- [ ] follow up sponsorship requests
- [ ] follow up financial requests
- [ ] follow up on Bevy

_______________________________

BG Edited to add:

- [ ] discuss PyLadies Silicon Valley expenditures request
- [ ] discuss PyLadies Paris expenditures request
- [ ] discuss PyLadies global expenditures request
- [ ] discuss PyLadies global hosting (for dynamic and static sites) expenditures

cc/ @pyladies/pyladies-global-admin

**Comment by BethanyG** [comment]
@Marie-L ....just for sanity sake, can we use the finance repo for finance tasks -- or link to them from this tracking issue?  Having two different task lists (and two different sets of notes) in two different repos is very hard to track and update.

**Comment by BethanyG** [comment]
@Marie-L  - not sure what happened to the invite, but I thought we were meeting today (June 13th at 12:30 PDT/8:30 BST), but did not see you online.  Looks like the invite went for Monday (the 14th)  instead -- but we've discussed not being able to meet at the time stated.  Please let me know when the next available meeting time is to discuss these issues.  Thanks!

**Comment by BethanyG** [comment]
Closing as no longer relevant.
