### ISSUE TITLE
Create Global council announcement schedule

### ISSUE THREAD

**Issue by MmeMarieLouise** [pyladies/global-organizing#119]
# Tasks

- [ ] Decide which order we'll make the initial announcements (summer post, bio post etc.)
- [ ] which global holidays will we make an announcement for ?
- [ ] when will Juliana make a complimentary on social media ?

cc/ @pyladies/pyladies-global-admin

**Comment by BethanyG** [comment]
Closing as there has been no movement since 2021.
