### ISSUE TITLE
Monthly Global Council Spotlight announcement

### ISSUE THREAD

**Issue by MmeMarieLouise** [pyladies/global-organizing#120]
# Tasks

- [ ] How can we highlight members ?
- [ ] Chapters ?
- [ ] Draft a template
- [ ] How can we promote community events ?
- [ ] at what point will we most each month (ie. 1st or 2nd week in the month) ?

cc/ @pyladies/pyladies-global-admin

**Comment by BethanyG** [comment]
Closing this since there has been no movement since 2021.  Once we get work going again, we can re-open or recreate.
