### ISSUE TITLE
Monthly PyLadies Meeting Notes: September 11, 2019

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#14]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

**Initial Details**

- Previous meeting issue link: #8 
- Current meeting attendees: @jackiekazil @trallard @elainewong @lorenanicole 

**Meeting Topics**

_Please add items as needed. If you add a topic please make sure to attend the meeting._

_New Business_

- [x] Review [RFC](https://github.com/pyladies/global-organizing/issues/11) and prepare next steps for moving the global board forward
  - [x] Should we start recruiting more global pyladies folks?
- [ ] Review the #9 feedback
- [ ] Can we create Zapier account for PyLadies? So far our bots are all Zapier-powered, but using my (@Mariatta) account. It would be great to have PyLadies' own account. There is 15% non profit discount https://zapier.com/non-profits/. More discussion captured: https://github.com/pyladies/global-organizing/issues/21
- [ ] We need a policy to review logos #22 ! Also, should we trademark the PyLadies face logo? Per this list it isn't trademarked: https://wiki.python.org/psf/TrademarksCommittee/Trademarks #22 
- [ ] New PyLadies chapter requests (#7): 
   - [x] Ognomoso, Nigeria (lautech, Ladoke Akintola University of Technology)
   - [x] Aba. Abia state, Nigeria (abiang)
   - [x] Orange County, USA
   - [x] Jakarta, Indonesia
- [ ] How do we control Slack invites? #21 
- [ ] Automation for Slack info #23 

_Old Business: Follow up items from prior meeting:_
  - [ ] Language on pyladies website #18 
  - [ ] Again meeting time ... it's a WIP but we should try to get a hold on this #16
  - [ ]

**Action Items and Assignees for Next Meeting**

Action Item| Owner | Relevant links | 
| --| --| --|
| Draft language for the RFC issue on how to select the board | @lorenanicole| #24 |
| Draft language for the RFC issue on project pillars | @lorenanicole | #26 |
| Data analysis on chapter surveys | @lorenanicole | #25 |
