### ISSUE TITLE
Monthly PyLadies Meeting Notes: Oct 11 2019

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#27]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

## Meeting has been pushed to Oct 11 2019! 

**Initial Details**

- Previous meeting issue link: #14 
- Current meeting attendees: 
   - @lorenanicole (PyLadies Chicago)
   - @deboraazevedo (PyLadies Brasil)
   - @georgically (PyLadies Bangkok)
   - @jesford (PyLadies Salt Lake City)
   - @elainewong  (PyLadies Toronto)
   - @trallard  (PyLadies northwest UK)
   - @bethanyg (PyLadies Oakland)

**Meeting Topics**

_Please add items as needed. If you add a topic please make sure to attend the meeting._

_New Business_

- [x] Review language for Oct 18 RFC: PyLadies Global Council Selection issue: https://github.com/pyladies/global-organizing/issues/24
- [x] Update Pyladies COC to use new PSF COC see: https://pyfound.blogspot.com/2019/09/the-python-software-foundation-has_24.html
- [x] Review language for Oct 18 RFC: PyLadies Project Teams issue: https://github.com/pyladies/global-organizing/issues/26
- [ ] Slack automation + Zapier -- moved to next month when @Mariatta can make mtg
- [ ] @lorenanicole is going to be working with a London based group to kick off a "Django Girls" but for data science workflows, anyone interested? -- agreed to open an issue

_Old Business: Follow up items from prior meeting:_
  - [ ] @Mariatta looks like we did create the 4 new chapters from Sept #14 but wanted clarification on the proper way to reboot? (@lorenanicole ) -- moved to next month when @Mariatta can make mtg
  - [ ] Do we want to add a second rotating time for these meetings: https://github.com/pyladies/global-organizing/issues/16 ?
  - [ ]
  - [ ]

**Action Items and Assignees for Next Meeting**

Action Item| Owner | Relevant links | 
| --| --| --|
| Open issue to explore Code of Conduct | @lorenanicole | --|
| Push convo on PyLadies membership language to issue | @lorenanicole | #6 |
| Please review language on issues #24 & #26 in the Google document linked | @trallard @elainewong @bethanyg @deboraazevedo @georgically @Mariatta @willingc @jackiekazil @ossanna16 @jesford | #24, #26 |
| Add @bethanyg @deboraazevedo @georgically @jesford PyLadies global organizing GitHub team |  @lorenanicole | N/A |
| Please review adding a second global meeting time | @trallard @elainewong @bethanyg @deboraazevedo @georgically @Mariatta @willingc @jackiekazil @ossanna16 @jesford | #16 |

**Comment by jackiekazil** [comment]
OMG I need a @jackie-bot.

**Comment by lorenanicole** [comment]
Haha it’s on my todo 

Sent from my iPhone

__________________________________________________

Lorena Mesa
Co-Organizer, PyLadies Chicago
Vice-Chair, Elect & Director, Python Software Foundation
www.lorenamesa.com
@loooorenanicole

Pronouns: she/her/hers Say what?
