### ISSUE TITLE
Monthly PyLadies Meeting Notes: Nov 13 2019

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#29]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

**Initial Details**

- Previous meeting issue link: #27 
- Current meeting attendees:

**Meeting Topics**

_Please add items as needed. If you add a topic please make sure to attend the meeting._

_New Business_

- [ ] Review issues for Oct 18 RFC PyLadies Global Council Selection #32 (@lorenanicole)

     - Proposal 3 seems to be preferred, blend of nomination(s) and election
     - Not all council should be up for re-election at same time -- proposal is four have 1 year term, five a 2 year term
     - No more than 33% of board should be from the same country
     - Should we extend this period or do we feel we can make a recommendation?

- [ ] Review issue for Oct 18 RFC Project teams #33 (@lorenanicole)
- [ ] Code of Conduct discussion (@lorenanicole) #30 
- [ ] PyLadies language on website: whom do we define as us? #8 (ALL)
- [ ] Slack invite policy #21 (ALL)
- [ ] Slack automation + Zapier  https://github.com/pyladies/global-organizing/issues/23 (@Mariatta)
- [ ] New PyLadies chapter requests (@elainewong / @Mariatta):
   - [ ] São Luís/Maranhão, Brazil
   - [ ] Congo-Brazzaville
   - [ ] Visakhapatnam/Andhra Pradesh/India
   - [ ] ASABA DELTA STATE NIGERIA
   - [ ] Princeton, NJ, U.S.A.
   - [ ] Lexington, KY, USA
   - [ ] São Bento do Sul/Santa Catarina/Brasil
   - [ ] Lusaka, Zambia
   - [ ] Florianópolis/Santa Catarina, Brazil
   - [ ] West Windsor, NJ
   - [ ] Thousand Oaks, Callifornia, USA
   - [ ] Winnipeg, MB. Canada
   - [ ] Karlsruhe, Germany
   - [ ] Bogotá, Colombia
   - [ ] Sergipe, Brazil
   - [ ] Hyderabad, India
   - [ ] Puebla, Mexico
   - [ ] San Diego Alcalá, Mexico
   - [ ] Sul de Minas Gerais. Brazil
   - [ ] São Bento do Sul/Santa Catarina/Brasil

- [ ] Do we have more Global interim members we want to add?
- [ ]

_Old Business: Follow up items from prior meeting:_
  - [ ] Publish some report on PyLadies surveys #25 (ALL)
  - [ ] Do we want to add a second rotating time for these meetings: #16  (ALL)
  - [ ] PyLadies Data Science tutorial  (@lorenanicole)
  - [ ]

**Action Items and Assignees for Next Meeting**

Action Item| Owner | Relevant links | 
| --| --| --|

**Comment by Ryllari** [comment]
Missing Sergipe/Brazil at new PyLadies chapters request

**Comment by Mariatta** [comment]
Thanks, I've added all the missing chapter requests

**Comment by Mariatta** [comment]
There are 20 pending new chapter requests, I would recommend handling the new chapter separately so the global meeting can focus on governance, not administration.

**Comment by treasurechristain** [comment]
> There are 20 pending new chapter requests, I would recommend handling the new chapter separately so the global meeting can focus on governance, not administration.

Yes, I agree with this. Let administration be different from governance to enhance easy balancing of duty/activity.
