### ISSUE TITLE
Monthly PyLadies Meeting Notes: December 11 2019 @ 16:00 PST

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#45]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

**Initial Details**

- Previous meeting issue link: 
    - Issue: #27 
    - Notes: [Here](https://github.com/pyladies/global-organizing/blob/master/notes/2019/13_11_2019.md)
- Current meeting attendees: @BethanyG @Mariatta @lorenanicole and Georgi Ker (PyLadies Bangkok) 

**Meeting Topics**

_Please add items as needed. If you add a topic please make sure to attend the meeting._

_New Business_

- [x] PyLadies Global Council [Timeline](https://github.com/pyladies/global-organizing/blob/master/notes/2019/13_11_2019.md#q-how-will-we-announce-the-election) (#46)  
- [x] PyLadies chapters: Should we allow country wide chapters? We need to write a policy to pass to the Project Admin & Logistics team to implement. (Issues: How to start a chapter: https://github.com/pyladies/project-admin-logisitics/issues/8, Country specific chapter: https://github.com/pyladies/project-admin-logisitics/issues/9, How to deactivate a chapter: https://github.com/pyladies/project-admin-logisitics/issues/10, How to make "unofficial" chapters official: https://github.com/pyladies/project-admin-logisitics/issues/11)
- [x] Building a PyLadies Member Database (https://github.com/pyladies/global-organizing/issues/54)
     - We will need this if the Council is to be chosen / partially chosen by election. 
- [x] Anyone else want to be an admin on this repo? We added @BethanyG. But the request can continue to be reviewed into the future.
- [x] Who wants to lead the Jan 8 2019 @ 10:00 PST meeting? @lorenanicole and @Mariatta have lead a few times and can help answer questions.

_Old Business: Follow up items from prior meeting:_
- [x] Review PyLadies Projects (#33) including: 
     - What's the standard setup for a project?
          - Slack channel named #project-{name}
         - Repo with same name
         - PyLadies GitHub team with write privilege
     - Projects started: Project Comms (#17) and Project Admin & Logistics (#3)
     - Next Project: We need to open the Project Infra / Tech (#35)
- [x] Review PyLadies Global Council (#32) including:
     - What next for this issue?
     - What's the status of translation?
     -  @lorenanicole opened this issue for voting https://github.com/pyladies/global-organizing/issues/50
- [X] Review Slack onboarding policy and tooling https://github.com/pyladies/global-organizing/issues/23

**Action Items and Assignees for Next Meeting**

Action Item| Owner | Relevant links | 
-- | --| -- |
| Kickoff various policy discussions on starting, deactivating, etc PyLadies Chapters | @mariata @pyladies/admin-and-logistics | How to start a chapter: https://github.com/pyladies/project-admin-logisitics/issues/8, Country specific chapter: https://github.com/pyladies/project-admin-logisitics/issues/9, How to deactivate a chapter: https://github.com/pyladies/project-admin-logisitics/issues/10, How to make "unofficial" chapters official: https://github.com/pyladies/project-admin-logisitics/issues/11 |
| Kickstart voting for PyLadies Global Council Election Process | @lorenanicole  | https://github.com/pyladies/global-organizing/issues/50 |
| Finish merging and review of Slack onboarding etiquette and welcome language | @BethanyG | https://github.com/pyladies/global-organizing/issues/23 |
| Start PyLadies Membership Database | @BethanyG @lorenanicole  | https://github.com/pyladies/global-organizing/issues/54 |

**Comment by willingc** [comment]
> Who wants to lead the Jan 8 2019 @ 10:00 PST meeting

Is this the same meeting or a different one?

**Comment by Mariatta** [comment]
I can't attend jan 8 meeting.

**Comment by lorenanicole** [comment]
> > Who wants to lead the Jan 8 2019 @ 10:00 PST meeting
> 
> Is this the same meeting or a different one?

This is the meeting agenda for Dec. I just added that note for the Jan 2020 meeting since it’d be great to have some other folks run the meeting! I do get tired of hearing my own voice after a while 🤣.

**Comment by gise** [comment]
I won't be able to attend the one in December as it's midnight to 1am in London time, but looking forward to the one in January! :)

**Comment by lorenanicole** [comment]
@gise thanks for the update! We always take notes (as you can see in the agenda above we link to the last month's issue and notes) and publish them in the Slack under `#feed-global-minutes`). We will continue to iterate on our times but to keep this globally inclusive, as best as we can, that is why are on a bimonthly time table (#16). 

Recording the meeting may be an option in the future, but that adds another manual process in which I think we should defer on until we get tooling in place for this.
