### ISSUE TITLE
PyLadies Global Election - Public Election Tracker Issue

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#59]
# PyLadies Global Election - Public Election Tracker Issue

## Questions to answer for Public Election
* What is the final timeline?
* Should voting will be open to any registered PyLadies member?
* What happens if there are ties?
* What tech should be used for voting?

## Deliverables
- [x] Create PyLadies member database: https://github.com/pyladies/global-organizing/issues/54
- [x] Decide voting policy @BethanyG to open issue (**Issue open in election website repo:**  https://github.com/pyladies/pyladies-elections-website-src/issues/32)
- [x] Decide tech for running election @lorenanicole to open PR 
- [ ] Review election website (e.g. voting policy, registering to run, etc)
- [ ] Determine nomination review process (e.g. nomination application, who reviews nominations, how vote on that) discuss at May 2020 Global mtg
      #future-of-us workgroup reviews applications, each submits a vote for any of the applicants they would like to see on the council. highest votes wins. in case of ties, we need a tie breaker resolution (random number generator). TLDR; we need an election judge.
- [ ] Outreach discuss at May 2020 Global mtg https://github.com/pyladies/project-communications/issues/24 due May 20th
      blog post **
      social media ** 
      slack 
      email members <-- ask email if we can email them 

### Hack session

@lorenanicole will work on Sun at 10:00 CT

issues to open:
- create forms
- put forms onto website
- add more photos to website
- review website for:
      - voting policy
      - explaining the council
      - faq page
- how to vote:
     - create screen cast of how to vote
     - in English the step by step for voting ** May 20
     - translate the step by step guide
- translation priority:
     - what is the council 
     - how to register to be considered for the council
- use psf election page as template 
     - todo: @lorenanicole find the psf voting policy

**Comment by lorenanicole** [comment]
# Should voting will be open to any registered PyLadies member?

I would advocate that voting should be open to any self identified PyLadies member registered in the database.

**Comment by Mariatta** [comment]
> should voting will be open to any registered PyLadies member?

1) How does one became registered as a PyLadies member? (I assume the will be a form). Does membership means they must be belonging to a chapter? (local/remote) or say if they are in PyLadies slack, and there is no local chapter in their area, can they still become a member?

2) Do we need to set a deadline, e.g must be registered before MMM, DD, YYYY in order to be eligible to receive the voting ballot? E.g. if they became a member after voting has started, can they still vote? 

> What tech should be used for voting?

The PSF uses Helios voting system, that seems to work and familiar to PSF members. Perhaps we should just use the same.

**Comment by pfctdayelise** [comment]
@lorenanicole Maybe it's paranoia but I was just thinking about how things like twitter are stormed with bots. Imagine if pyladies got flooded with fake registrations that in the future were used to put some, IDK, MRA person that had nothing to do with pyladies, into the council.

It's generally easier to extend voting rights than to take them away, so maybe start cautiously with people that have somehow been 'vetted' by others. (eg core team vets chapter leaders, chapter leaders vet people in their chapters) It's a lot more work though...

@Mariatta I think your Qs are covered in #54 

Is Helios based on a first-past-the-post method or something else? (I'm really surprised this isn't prominent on the Helios site.) How does it work when there are multiple seats, is it just first-N-past-the-post?

**Comment by lorenanicole** [comment]
@pfctdayelise regarding:

> Maybe it's paranoia but I was just thinking about how things like twitter are stormed with bots. Imagine if pyladies got flooded with fake registrations that in the future were used to put some, IDK, MRA person that had nothing to do with pyladies, into the council.

The PSF doesn't do vetting per say, instead there's just a registration form on the website. That said, being cognizant of groups for underrepresented people being targeted is a huge point to say being more thoughtful is better.

So that said, are you suggesting that instead of an open link online instead we can have chapter organizers disseminate a registration form? I am 👍 that. However what is someone is a PyLadies member but there's no local PyLadies chapter for them to participate in?

**Comment by Mariatta** [comment]
I found the following documentation on what happens in case of a tie in PSF's board of directors election: https://github.com/python/psf-election#in-the-event-of-a-tie not sure if this is up to date information.

Other org like Open Source Initiative does run-off voting in case of the tie. I think that's an option as well. But perhaps we need to choose upfront, whether we will do the run-off, or doing what the PSF does (use a script to break a tie)

**Comment by pfctdayelise** [comment]
> The PSF doesn't do vetting per say, instead there's just a registration form on the website. 

But Basic members can't vote. To vote you need to be Supporting (donate money, which is automatic but adds enough friction to stop bots) or Managing/Contributing/Fellow.

Well I guess there is one form for Managing/Contributing, maybe it doesn't get meaningfully reviewed? I was assuming someone at least glanced at it before someone got 'approved' in one of those categories.

> So that said, are you suggesting that instead of an open link online instead we can have chapter organizers disseminate a registration form? I am 👍 that. 

Having diff organisers disseminate a form sounds difficult. I was thinking they could nominate a chapter that they have participated in and then the responsibility for saying 'have I ever heard of this person' would fall to the organisers of the chapter they nominated.

> However what is someone is a PyLadies member but there's no local PyLadies chapter for them to participate in? In considering precedence, anyone can claim to be a PyLadies member for the PyLadies financial sponsorship opportunities for PyCon US. If we start moving away from that we are in effect starting new precedence here.

Well, there is pyladies 'remote'. But it comes back to how do we actually consider someone part of our community? What does participation in the pyladies community look like? 
I would presume it includes some Python at some level. Maybe the simplest way to do this would be have a write-in field 'What does participation in the pyladies community mean to you?' which is reviewed for some comprehensible mention of Python related activities.

**Comment by lorenanicole** [comment]
Some thoughts:

> Having diff organisers disseminate a form sounds difficult. I was thinking they could nominate a chapter that they have participated in and then the responsibility for saying 'have I ever heard of this person' would fall to the organisers of the chapter they nominated.

I'm +1 on the format being: someone applies to be a member, selects a chapter, the chapter organizers "review".

That said, though, I can say as a community organizer for 5+ years for PyLadies Chicago, I definitely cannot recall all our members. I would probably at least do something like: confirm they are in the slack, or they are in the meetup.

Would some minimal review like that work for you?

> Maybe the simplest way to do this would be have a write-in field 'What does participation in the pyladies community mean to you?' which is reviewed for some comprehensible mention of Python related activities.

I like this idea! I think we should error on being more inclusive rather than exclusive.

**Comment by pfctdayelise** [comment]
> That said, though, I can say as a community organizer for 5+ years for PyLadies Chicago, I definitely cannot recall all our members. I would probably at least do something like: confirm they are in the slack, or they are in the meetup.
> 
> Would some minimal review like that work for you?

Yes, that is exactly what I would do (additionally I would check they have been a meetup member since before the election date).

**Comment by Mariatta** [comment]
Sorry in advance for long reply, lots of thoughts and concerns:

- I'm actually a little bit concerned with burdening local volunteer chapter leaders into spending time reviewing/confirming membership. Each chapter operate differently, and not all chapters even use Meetup. (check all listed chapters here: https://github.com/pyladies/pyladies/blob/master/www/config.yml, not everyone has a meetup associated).

- We also know that out of hundreds of PyLadies chapters, only 33 participated in the past voting period. And that was after lots of outreach on our part, we kept reminding folks to review proposals, and to review. Based on that experience, I'm sorry to say but I'm a bit skeptical. How can we be sure that each chapter leaders is willing to participate on their members' behalf? How can we be sure that they will be able to review/confirm memberships on time for the election? 

- I don't think membership to a specific chapter should be a requirement in becoming a PyLady.

- If there is no local chapter in their area, I don't think they should be defaulted to being a member of the remote chapter. As I remember it, the remote chapter is also ran by a couple ladies, I'm concerned with burdening them with additional responsibilities and needing to now keep track of all the members without local chapters.

- I would agree to having condition like: "you must be a registered as a PyLadies member before election starts in order to vote" (and in order to be  nominated). 

- I believe that the only people we want to exclude from the election are really "bots". We should not add more barriers to self-identified PyLady into participating and voting.

- I would like to see less manual work on any of us. Perhaps for each member who want to vote/be elected, they should provide us with their GitHub username, and they should have 2FA enabled in their GitHub account. I can write a script to check if the GitHub user is valid (exists), and whether 2FA is enabled. This should reduce the number of bots/spam registrations.

**Comment by trallard** [comment]
I agree with @mariatta  on the points above I would not like this to turn into extra burden for both the local organisers or any of us. 

The GitHub option sounds like a good one to reduce the number of bots. 
I would agree also on having those being nominated mainly as a PyLadies member and have some way of verifying this info (this should be easier than verifying the info of all the ones willing to vote)

**Comment by pfctdayelise** [comment]
@Mariatta fair points. Is requiring a github account a reasonable burden? There may be some people that have closed their account for ethical reasons...on balance, I would be prepared to defend that requirement as a reasonable one.

**Comment by sleepypioneer** [comment]
@lorenanicole could this issue be closed as it appears to have been moved to Done on the project board? Perhaps however there is a reason to keep the issue open?

**Comment by BethanyG** [comment]
@sleepypioneer  -- Thanks for pointing out these open issues!  I am going to go through and do some general housekeeping/closing.  😄  We can always refer back/reopen anything if its needed in the future.
