### ISSUE TITLE
Monthly PyLadies Meeting Notes: April 8, 2020  @ 4pm PT | 6pm CT | 12am UTC

### ISSUE THREAD

**Issue by BethanyG** [pyladies/global-organizing#64]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

# PyLadies Global Meeting

- Date:   April 8, 2020  @ 4pm PT | 6pm CT | 12am UTC
- Previous meeting issue link: https://github.com/pyladies/global-organizing/issues/62
- Current meeting attendees:

## Agenda

_Please add items as needed. If you add a topic please make sure to attend the meeting._

### Project Updates
1. Project Comms (Slack: #project-communication / Repo: https://github.com/pyladies/project-communications)

2. Project Admin & Logistics (Slack: #project-admin-logistics / Repo: https://github.com/pyladies/project-admin-logisitics )

3. Project Tech & Infra (Slack: #project-tech-infra / Repo: https://github.com/pyladies/pyladies )

### Review Actions Items from Last Meeting

Action Item| Owner | Relevant links | Completed
| --| --| --| --|

### New Business

- [ ]  PyLadies Election Update https://github.com/pyladies/global-organizing/issues/59
    - Voting policy:
       - Is it written?
       - Is there a pull request?
    - Tech to run election:
      - Use Helio like PSF for an election
      - Use PSF Director of Infra to be election coordinator
      - Confirm run off rules
    -   Tech - Public election page:
        - Where should it live?
    - Nomination
        - We need to write an application for individuals to nominate
        - We need to determine how voting on nomination works
    - Outreach
        - Need blog post for election see: pyladies/project-communications#24
- [x] Update on PyLadies Members registered
        
| Total | Type| Language | 
| -- | -- |  -- |
| 35 | Basic | English |
| 9  | Basic | Spanish |
| 109 | Basic | Portuguese |
| 2 |  Basic | French  |
| 155 | Total | All |

| Total | Type| Language | 
| -- | -- |  -- |
| 89 | Voting | English |
|  5 | Voting | Spanish |
| 94 | Voting | Portuguese |
| 1 | Voting | Chinese |
 | 189 | Total  | All |

- [ ] Can we install Icebreakers app on Slack?  (brought up by @mei-li in organizers slack channel) @Mariatta 

Concern: 
It needs lots of permissions. 

> On behalf of the app:
> - View messages and other content in public channels that Icebreakers has been added to channels:history
> - View messages and other content in direct messages that Icebreakers has been added to im:history
> - View files shared in channels and conversations that Icebreakers has been added to files:read
> - View people in the workspace users:read
> - View basic information about public channels in the workspace channels:read
> - View basic information about private channels that Icebreakers has been added to groups:read
> - View the name, email domain, and icon for workspaces Icebreakers is connected to team:read
> - View email addresses of people in the workspace users:read.email
> - Send messages as `@icebreakers` chat:write
- [ ] PyLadies Virtual Cafe https://github.com/pyladies/global-organizing/issues/65
- [ ] Tweet from PyLadies https://github.com/pyladies/global-organizing/issues/65

### Old Business: Follow up items from prior meeting:
  - [ ] 
  - [ ]

### Action Items and Assignees for Next Meeting

Action Item| Owner | Relevant links | 
| --| --| --|

@pyladies/pyladies-global-contributors 
@pyladies/pyladies-global-admin
