### ISSUE TITLE
Monthly PyLadies Meeting Notes: August 14 2019

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#8]
_This template should be used (edited) the month prior and during the meeting. This will ensure we can address all topics added throughout the month; as well as provide minutes and follow up after the meeting is held._

**Initial Details**

- Previous meeting issue link: https://github.com/pyladies/global-organizing/issues/4
- Current meeting attendees:

**Meeting Topics**

_Please add items as needed. If you add a topic please make sure to attend the meeting._

_New Business_

- [x] New PyLadies chapter requests: 
   - [x] Goa, India
   - [x] Rio Grande Valley, TX
   - [x] Bangkok, Thailand
   - [x] Windhoek, Namibia

- [x] Prepare communication plan around August 15 2019 email (@lorenanicole) - made issue #15 
   - Tweet
   - Google group retirement
   - PyLadies Slack, do we want to keep this as an open Slack or move to request to join / approval method?
   - Should we add this to a blog post? For example, PSF blog?
- [x] Propose alternate global meeting time so non-US members can join (@Mariatta) - see https://github.com/pyladies/global-organizing/issues/16
   - Should this be a video/phone chat or via Slack?
- Slack has global restrictions against Iran etc and those members cannot join PyLadies Slack, do we want to investigate this further? (@lorenanicole) 
  - Can we setup an IRC bridge for those impacted to be a part of our Slack community? 
  - TODO: For the future communication project pillar they should investigate tooling for the community including adding minutes to the pyladies website.
  - Make an issue for communications project group, will capture this issue here and defer work/decisions until after Sept 15th when the group has made decisions on global leadership formation - see https://github.com/pyladies/global-organizing/issues/17
- Making PyLadies Slack a paid plan (@lorenanicole)
  - Investigate pricing - condensed into issue https://github.com/pyladies/global-organizing/issues/17
- [x] Looking at website language so it is super obvious that pyladies welcomes all ladies - including trans women and non-binary folk. - see https://github.com/pyladies/global-organizing/issues/18
- [x]  Code of Conduct in the Community

_Old Business: Follow up items from prior meeting:_
  - [x] Aug 15 2019 email update to all PyLadies chapters (everyone!!)
    - Email and forms to be sent re: pyladies announcement (@mariatta, @katialira)
    - Review email language in #9 
- [ ] 

**Action Items and Assignees for Next Meeting**

Action Item| Owner | Relevant links | 
| --| --| --|
Email the Aug 15 2019 email | @Mariatta | #9 
Send out communication to all spaces for Aug 15 2019 email | @lorenanicole | #15 
Communications Project tracker issue - what should they work on | unassigned | #17 
Update language on PyLadies website on about changing women more inclusive language | unassigned | #18 
Upload Aug 15 2019 minutes | @Mariatta | --
Code of Conduct in the Community | @elainewong @Mariatta Anwesha | --
